### ISSUE TITLE
Allow for local mode

### ISSUE THREAD

**Issue by killermoehre** [HewlettPackard/ilo-ansible-collection#23]
With the `ilorest` tool provided by https://downloads.linux.hpe.com/SDR/repo/ilorest/ one does not need to connect via the remote interface, but can use a local connection mode.

Can the collection be used with the local mode?

**Comment by donzef** [comment]
I doubt about that because this Ansible collection uses the DMTF Redfish Python Library and not the HPE Redfish Python Library that iLOrest is based upon. @rajeevkallur should be able to confirm/infirm.

That said, it is possible to access the iLO via the Host Interface, also called [Virtual NIC](https://support.hpe.com/hpesc/public/docDisplay?docId=sd00002007en_us&docLocale=en_US&page=GUID-D3413492-02CD-4AB2-A2DA-B3E9F8F994B2.html)

This interface is completely internal.

**Comment by killermoehre** [comment]
Does this interface require credentials? Because this is one of the really nice features of the local_connect, that you *don't* need them.

**Comment by rajeevkallur** [comment]
Yes, currently vnic require credentials.

**Comment by killermoehre** [comment]
Bummer, but ok. Closing this as not possible.
